INSERT INTO EXCHANGE_VALUE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,PORT)
VALUES(10001,'USD','INR',65,0);
INSERT INTO EXCHANGE_VALUE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,PORT)
VALUES(10002,'EUR','INR',75,0);
INSERT INTO EXCHANGE_VALUE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE,PORT)
VALUES(10003,'AUD','INR',25,0);